#spring.application.name=shopify-ingestion
#
#server.port=8080
#
#spring.datasource.url=jdbc:mysql://localhost:3306/xeno_shopify
#spring.datasource.username=xeno_user
#spring.datasource.password=xeno123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.format_sql=true
## Shopify Configuration
#shopify.store.url=xeno-fde-jaswanth.myshopify.com
#shopify.access.token=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
#
## Scheduler Configuration
## Enable/Disable scheduler
#spring.task.scheduling.enabled=true
#
## Thread pool size for scheduled tasks
#spring.task.scheduling.pool.size=5
#
#spring.data.redis.port=6380
## Redis Configuration
#spring.data.redis.host=localhost
#spring.cache.type=redis
#spring.cache.redis.time-to-live=3600000

#--------------
# Application
spring.application.name=shopify-ingestion

# Railway gives PORT dynamically
server.port=${PORT:8080}

# ===== MySQL Configuration (Railway) =====
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/xeno_shopify}
spring.datasource.username=${MYSQLUSER:xeno_user}
spring.datasource.password=${MYSQLPASSWORD:xeno123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== Shopify =====
shopify.store.url=${SHOPIFY_STORE_URL:xeno-fde-jaswanth.myshopify.com}
shopify.access.token=${SHOPIFY_ACCESS_TOKEN:your-token}

# ===== Scheduler =====
spring.task.scheduling.enabled=true
spring.task.scheduling.pool.size=5

# ===== Redis (Optional) =====
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6380}
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000
